#!/usr/bin/env python3
"""Generate test/test_ccm/vectors_ccm.h.

Emits known-answer vectors for the waymesh_crypto AES core + AES-CCM AEAD:
  - AES block (FIPS-197 Appendix C) — AES-128/256 single-block ECB.
  - AES-CCM — RFC 3610 packet vectors #1/#2 (public), cross-checked against
    pyca/cryptography, plus Waymesh-wire vectors at our exact params (nonce 13,
    tag 4) for AES-128 and AES-256, generated by pyca.

Three-way agreement (RFC 3610 published <-> pyca <-> our C lib) anchors the
CCM construction. AES-CTR/nonce byte-match with Meshtastic is a separate TX-path
concern (step 5), not exercised here. Requires: pip install cryptography.
"""
import sys
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.ciphers.aead import AESCCM

H = lambda s: bytes.fromhex(s.replace(" ", ""))


def aes_ecb(key: bytes, pt: bytes) -> bytes:
    c = Cipher(algorithms.AES(key), modes.ECB()).encryptor()
    return c.update(pt) + c.finalize()


# --- AES block KATs (FIPS-197 Appendix C) ---
AES_BLOCK = [
    ("FIPS-197 C.1 AES-128", H("000102030405060708090a0b0c0d0e0f"),
     H("00112233445566778899aabbccddeeff")),
    ("FIPS-197 C.3 AES-256",
     H("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"),
     H("00112233445566778899aabbccddeeff")),
]
# Cross-check against the published FIPS-197 answers.
_FIPS = {16: "69c4e0d86a7b0430d8cdb78070b4c55a",
         32: "8ea2b7ca516745bfeafc49904b496089"}
for _name, _k, _pt in AES_BLOCK:
    assert aes_ecb(_k, _pt).hex() == _FIPS[len(_k)], _name

# --- CCM KATs ---
# RFC 3610 §8 packet vectors #1 and #2 (public, tag length M=8, nonce 13 bytes).
RFC_KEY = H("C0C1C2C3 C4C5C6C7 C8C9CACB CCCDCECF")
CCM = []  # (label, key, nonce, aad, pt, taglen)
CCM.append(("RFC3610 #1", RFC_KEY,
            H("00000003 020100A0 A1A2A3A4 A5"),
            H("00010203 04050607"),
            H("08090A0B 0C0D0E0F 10111213 14151617 18191A1B 1C1D1E"), 8))
CCM.append(("RFC3610 #2", RFC_KEY,
            H("00000004 030201A0 A1A2A3A4 A5"),
            H("00010203 04050607"),
            H("08090A0B 0C0D0E0F 10111213 14151617 18191A1B 1C1D1E1F"), 8))
# Cross-check the RFC vectors against pyca before relying on them.
_RFC_OUT = {
    "RFC3610 #1": "588C979A 61C663D2 F066D0C2 C0F98980 6D5F6B61 DAC38417 E8D12CFD F926E0",
    "RFC3610 #2": "72C91A36 E135F8CF 291CA894 085C87E3 CC15C439 C9E43A3B A091D56E 10400916",
}
for label, key, nonce, aad, pt, taglen in CCM:
    got = AESCCM(key, tag_length=taglen).encrypt(nonce, pt, aad)
    assert got.hex() == H(_RFC_OUT[label]).hex(), f"{label} != RFC3610"

# Waymesh-wire vectors: nonce 13 = [chanHash][srcNodeID LE][packetId LE][pad4];
# aad 11 = header[1..11] = ver,chanHash,flags,srcNodeID LE,packetId LE; tag 4.
WM_NONCE = H("08 44332211 39050000 00000000")
WM_AAD = H("02 08 07 44332211 39050000")
WM_PT = H("80969800 7B0C0000 0500")  # 10-byte POS-ish payload
CCM.append(("Waymesh AES-128 (nonce13,tag4)", H("d4f1bb3a20290759f0bcffabcf4e6901"),
            WM_NONCE, WM_AAD, WM_PT, 4))
CCM.append(("Waymesh AES-256 (nonce13,tag4)",
            H("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"),
            WM_NONCE, WM_AAD, WM_PT, 4))


def carr(b: bytes) -> str:
    return ",".join("0x%02x" % x for x in b)


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else None
    f = open(out, "w") if out else sys.stdout
    p = lambda *a: print(*a, file=f)
    p("/* GENERATED — do not edit. AES block + AES-CCM known-answer vectors.")
    p(" * Produced by tools/gen_ccm_vectors.py (pyca/cryptography); AES from")
    p(" * FIPS-197 App.C, CCM from RFC 3610 + Waymesh-wire params (nonce 13,")
    p(" * tag 4). Regenerate after changing inputs. */")
    p("#ifndef WAYMESH_VECTORS_CCM_H")
    p("#define WAYMESH_VECTORS_CCM_H")
    p("#include <stddef.h>\n#include <stdint.h>\n")
    p("typedef struct { const char *label; size_t key_len;")
    p("  uint8_t key[32], pt[16], ct[16]; } wm_aes_block_vec_t;\n")
    p("static const wm_aes_block_vec_t WM_AES_BLOCK_VECS[] = {")
    for name, k, pt in AES_BLOCK:
        p('  { "%s", %d, {%s}, {%s}, {%s} },' %
          (name, len(k), carr(k), carr(pt), carr(aes_ecb(k, pt))))
    p("};")
    p("#define WM_AES_BLOCK_VEC_COUNT %d\n" % len(AES_BLOCK))

    p("typedef struct { const char *label; size_t key_len, nonce_len, aad_len,")
    p("  pt_len, tag_len; uint8_t key[32], nonce[13], aad[16], pt[32], ct[32],")
    p("  tag[16]; } wm_ccm_vec_t;\n")
    p("static const wm_ccm_vec_t WM_CCM_VECS[] = {")
    for label, key, nonce, aad, pt, taglen in CCM:
        out_bytes = AESCCM(key, tag_length=taglen).encrypt(nonce, pt, aad)
        ct, tag = out_bytes[:len(pt)], out_bytes[len(pt):]
        p('  { "%s", %d,%d,%d,%d,%d, {%s},{%s},{%s},{%s},{%s},{%s} },' %
          (label, len(key), len(nonce), len(aad), len(pt), taglen,
           carr(key), carr(nonce), carr(aad), carr(pt), carr(ct), carr(tag)))
    p("};")
    p("#define WM_CCM_VEC_COUNT %d\n" % len(CCM))
    p("#endif /* WAYMESH_VECTORS_CCM_H */")
    if out:
        f.close()
        print("Wrote", out)


if __name__ == "__main__":
    main()
