/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESHTASTIC_WAYMESH_MESH_PB_H_INCLUDED
#define PB_MESHTASTIC_WAYMESH_MESH_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _meshtastic_Position {
    int32_t latitude_i; /* degrees * 1e7 (identical to our LP encoding) */
    int32_t longitude_i; /* degrees * 1e7 */
    int32_t altitude; /* meters */
    uint32_t time; /* epoch seconds */
    uint32_t location_source; /* Position.LocSource (LOC_INTERNAL = 2) */
    uint32_t sats_in_view;
} meshtastic_Position;

typedef struct _meshtastic_User {
    char id[16]; /* "!aabbccdd" */
    char long_name[40];
    char short_name[8];
    uint32_t hw_model; /* HardwareModel (PRIVATE_HW = 255) */
    uint32_t role; /* Config.DeviceConfig.Role (CLIENT = 0) */
} meshtastic_User;

typedef PB_BYTES_ARRAY_T(256) meshtastic_Data_payload_t;
typedef struct _meshtastic_Data {
    uint32_t portnum; /* PortNum: TEXT=1, POSITION=3, NODEINFO=4 */
    meshtastic_Data_payload_t payload;
} meshtastic_Data;

typedef PB_BYTES_ARRAY_T(256) meshtastic_MeshPacket_encrypted_t;
typedef struct _meshtastic_MeshPacket {
    uint32_t from;
    uint32_t to;
    uint32_t channel;
    pb_size_t which_payload_variant;
    union {
        meshtastic_Data decoded;
        meshtastic_MeshPacket_encrypted_t encrypted;
    } payload_variant;
    uint32_t id;
    uint32_t rx_time;
    float rx_snr;
    uint32_t hop_limit;
    bool want_ack;
    int32_t rx_rssi;
    uint32_t hop_start;
} meshtastic_MeshPacket;

typedef struct _meshtastic_MyNodeInfo {
    uint32_t my_node_num;
    uint32_t reboot_count;
    uint32_t min_app_version;
} meshtastic_MyNodeInfo;

typedef struct _meshtastic_NodeInfo {
    uint32_t num;
    bool has_user;
    meshtastic_User user;
    bool has_position;
    meshtastic_Position position;
    float snr;
    uint32_t last_heard;
    uint32_t channel;
} meshtastic_NodeInfo;

typedef struct _meshtastic_DeviceMetadata {
    char firmware_version[24];
    uint32_t device_state_version;
    bool canShutdown;
    bool hasWifi;
    bool hasBluetooth;
    bool hasEthernet;
    uint32_t role; /* Config.DeviceConfig.Role */
    uint32_t position_flags;
    uint32_t hw_model; /* HardwareModel */
    bool hasRemoteHardware;
} meshtastic_DeviceMetadata;

typedef struct _meshtastic_ToRadio {
    pb_size_t which_payload_variant;
    union {
        meshtastic_MeshPacket packet;
        uint32_t want_config_id;
        bool disconnect;
    } payload_variant;
} meshtastic_ToRadio;

typedef struct _meshtastic_FromRadio {
    uint32_t id;
    pb_size_t which_payload_variant;
    union {
        meshtastic_MeshPacket packet;
        meshtastic_MyNodeInfo my_info;
        meshtastic_NodeInfo node_info;
        uint32_t config_complete_id;
        bool rebooted;
        meshtastic_DeviceMetadata metadata;
    } payload_variant;
} meshtastic_FromRadio;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define meshtastic_Position_init_default         {0, 0, 0, 0, 0, 0}
#define meshtastic_User_init_default             {"", "", "", 0, 0}
#define meshtastic_Data_init_default             {0, {0, {0}}}
#define meshtastic_MeshPacket_init_default       {0, 0, 0, 0, {meshtastic_Data_init_default}, 0, 0, 0, 0, 0, 0, 0}
#define meshtastic_MyNodeInfo_init_default       {0, 0, 0}
#define meshtastic_NodeInfo_init_default         {0, false, meshtastic_User_init_default, false, meshtastic_Position_init_default, 0, 0, 0}
#define meshtastic_DeviceMetadata_init_default   {"", 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define meshtastic_ToRadio_init_default          {0, {meshtastic_MeshPacket_init_default}}
#define meshtastic_FromRadio_init_default        {0, 0, {meshtastic_MeshPacket_init_default}}
#define meshtastic_Position_init_zero            {0, 0, 0, 0, 0, 0}
#define meshtastic_User_init_zero                {"", "", "", 0, 0}
#define meshtastic_Data_init_zero                {0, {0, {0}}}
#define meshtastic_MeshPacket_init_zero          {0, 0, 0, 0, {meshtastic_Data_init_zero}, 0, 0, 0, 0, 0, 0, 0}
#define meshtastic_MyNodeInfo_init_zero          {0, 0, 0}
#define meshtastic_NodeInfo_init_zero            {0, false, meshtastic_User_init_zero, false, meshtastic_Position_init_zero, 0, 0, 0}
#define meshtastic_DeviceMetadata_init_zero      {"", 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define meshtastic_ToRadio_init_zero             {0, {meshtastic_MeshPacket_init_zero}}
#define meshtastic_FromRadio_init_zero           {0, 0, {meshtastic_MeshPacket_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define meshtastic_Position_latitude_i_tag       1
#define meshtastic_Position_longitude_i_tag      2
#define meshtastic_Position_altitude_tag         3
#define meshtastic_Position_time_tag             4
#define meshtastic_Position_location_source_tag  5
#define meshtastic_Position_sats_in_view_tag     19
#define meshtastic_User_id_tag                   1
#define meshtastic_User_long_name_tag            2
#define meshtastic_User_short_name_tag           3
#define meshtastic_User_hw_model_tag             5
#define meshtastic_User_role_tag                 7
#define meshtastic_Data_portnum_tag              1
#define meshtastic_Data_payload_tag              2
#define meshtastic_MeshPacket_from_tag           1
#define meshtastic_MeshPacket_to_tag             2
#define meshtastic_MeshPacket_channel_tag        3
#define meshtastic_MeshPacket_decoded_tag        4
#define meshtastic_MeshPacket_encrypted_tag      5
#define meshtastic_MeshPacket_id_tag             6
#define meshtastic_MeshPacket_rx_time_tag        7
#define meshtastic_MeshPacket_rx_snr_tag         8
#define meshtastic_MeshPacket_hop_limit_tag      9
#define meshtastic_MeshPacket_want_ack_tag       10
#define meshtastic_MeshPacket_rx_rssi_tag        12
#define meshtastic_MeshPacket_hop_start_tag      15
#define meshtastic_MyNodeInfo_my_node_num_tag    1
#define meshtastic_MyNodeInfo_reboot_count_tag   8
#define meshtastic_MyNodeInfo_min_app_version_tag 11
#define meshtastic_NodeInfo_num_tag              1
#define meshtastic_NodeInfo_user_tag             2
#define meshtastic_NodeInfo_position_tag         3
#define meshtastic_NodeInfo_snr_tag              4
#define meshtastic_NodeInfo_last_heard_tag       5
#define meshtastic_NodeInfo_channel_tag          7
#define meshtastic_DeviceMetadata_firmware_version_tag 1
#define meshtastic_DeviceMetadata_device_state_version_tag 2
#define meshtastic_DeviceMetadata_canShutdown_tag 3
#define meshtastic_DeviceMetadata_hasWifi_tag    4
#define meshtastic_DeviceMetadata_hasBluetooth_tag 5
#define meshtastic_DeviceMetadata_hasEthernet_tag 6
#define meshtastic_DeviceMetadata_role_tag       7
#define meshtastic_DeviceMetadata_position_flags_tag 8
#define meshtastic_DeviceMetadata_hw_model_tag   9
#define meshtastic_DeviceMetadata_hasRemoteHardware_tag 10
#define meshtastic_ToRadio_packet_tag            1
#define meshtastic_ToRadio_want_config_id_tag    3
#define meshtastic_ToRadio_disconnect_tag        4
#define meshtastic_FromRadio_id_tag              1
#define meshtastic_FromRadio_packet_tag          2
#define meshtastic_FromRadio_my_info_tag         3
#define meshtastic_FromRadio_node_info_tag       4
#define meshtastic_FromRadio_config_complete_id_tag 7
#define meshtastic_FromRadio_rebooted_tag        8
#define meshtastic_FromRadio_metadata_tag        13

/* Struct field encoding specification for nanopb */
#define meshtastic_Position_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SFIXED32, latitude_i,        1) \
X(a, STATIC,   SINGULAR, SFIXED32, longitude_i,       2) \
X(a, STATIC,   SINGULAR, INT32,    altitude,          3) \
X(a, STATIC,   SINGULAR, FIXED32,  time,              4) \
X(a, STATIC,   SINGULAR, UINT32,   location_source,   5) \
X(a, STATIC,   SINGULAR, UINT32,   sats_in_view,     19)
#define meshtastic_Position_CALLBACK NULL
#define meshtastic_Position_DEFAULT NULL

#define meshtastic_User_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   long_name,         2) \
X(a, STATIC,   SINGULAR, STRING,   short_name,        3) \
X(a, STATIC,   SINGULAR, UINT32,   hw_model,          5) \
X(a, STATIC,   SINGULAR, UINT32,   role,              7)
#define meshtastic_User_CALLBACK NULL
#define meshtastic_User_DEFAULT NULL

#define meshtastic_Data_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   portnum,           1) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           2)
#define meshtastic_Data_CALLBACK NULL
#define meshtastic_Data_DEFAULT NULL

#define meshtastic_MeshPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  from,              1) \
X(a, STATIC,   SINGULAR, FIXED32,  to,                2) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload_variant,decoded,payload_variant.decoded),   4) \
X(a, STATIC,   ONEOF,    BYTES,    (payload_variant,encrypted,payload_variant.encrypted),   5) \
X(a, STATIC,   SINGULAR, FIXED32,  id,                6) \
X(a, STATIC,   SINGULAR, FIXED32,  rx_time,           7) \
X(a, STATIC,   SINGULAR, FLOAT,    rx_snr,            8) \
X(a, STATIC,   SINGULAR, UINT32,   hop_limit,         9) \
X(a, STATIC,   SINGULAR, BOOL,     want_ack,         10) \
X(a, STATIC,   SINGULAR, INT32,    rx_rssi,          12) \
X(a, STATIC,   SINGULAR, UINT32,   hop_start,        15)
#define meshtastic_MeshPacket_CALLBACK NULL
#define meshtastic_MeshPacket_DEFAULT NULL
#define meshtastic_MeshPacket_payload_variant_decoded_MSGTYPE meshtastic_Data

#define meshtastic_MyNodeInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   my_node_num,       1) \
X(a, STATIC,   SINGULAR, UINT32,   reboot_count,      8) \
X(a, STATIC,   SINGULAR, UINT32,   min_app_version,  11)
#define meshtastic_MyNodeInfo_CALLBACK NULL
#define meshtastic_MyNodeInfo_DEFAULT NULL

#define meshtastic_NodeInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   num,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          3) \
X(a, STATIC,   SINGULAR, FLOAT,    snr,               4) \
X(a, STATIC,   SINGULAR, FIXED32,  last_heard,        5) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           7)
#define meshtastic_NodeInfo_CALLBACK NULL
#define meshtastic_NodeInfo_DEFAULT NULL
#define meshtastic_NodeInfo_user_MSGTYPE meshtastic_User
#define meshtastic_NodeInfo_position_MSGTYPE meshtastic_Position

#define meshtastic_DeviceMetadata_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   1) \
X(a, STATIC,   SINGULAR, UINT32,   device_state_version,   2) \
X(a, STATIC,   SINGULAR, BOOL,     canShutdown,       3) \
X(a, STATIC,   SINGULAR, BOOL,     hasWifi,           4) \
X(a, STATIC,   SINGULAR, BOOL,     hasBluetooth,      5) \
X(a, STATIC,   SINGULAR, BOOL,     hasEthernet,       6) \
X(a, STATIC,   SINGULAR, UINT32,   role,              7) \
X(a, STATIC,   SINGULAR, UINT32,   position_flags,    8) \
X(a, STATIC,   SINGULAR, UINT32,   hw_model,          9) \
X(a, STATIC,   SINGULAR, BOOL,     hasRemoteHardware,  10)
#define meshtastic_DeviceMetadata_CALLBACK NULL
#define meshtastic_DeviceMetadata_DEFAULT NULL

#define meshtastic_ToRadio_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload_variant,packet,payload_variant.packet),   1) \
X(a, STATIC,   ONEOF,    UINT32,   (payload_variant,want_config_id,payload_variant.want_config_id),   3) \
X(a, STATIC,   ONEOF,    BOOL,     (payload_variant,disconnect,payload_variant.disconnect),   4)
#define meshtastic_ToRadio_CALLBACK NULL
#define meshtastic_ToRadio_DEFAULT NULL
#define meshtastic_ToRadio_payload_variant_packet_MSGTYPE meshtastic_MeshPacket

#define meshtastic_FromRadio_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload_variant,packet,payload_variant.packet),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload_variant,my_info,payload_variant.my_info),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload_variant,node_info,payload_variant.node_info),   4) \
X(a, STATIC,   ONEOF,    UINT32,   (payload_variant,config_complete_id,payload_variant.config_complete_id),   7) \
X(a, STATIC,   ONEOF,    BOOL,     (payload_variant,rebooted,payload_variant.rebooted),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload_variant,metadata,payload_variant.metadata),  13)
#define meshtastic_FromRadio_CALLBACK NULL
#define meshtastic_FromRadio_DEFAULT NULL
#define meshtastic_FromRadio_payload_variant_packet_MSGTYPE meshtastic_MeshPacket
#define meshtastic_FromRadio_payload_variant_my_info_MSGTYPE meshtastic_MyNodeInfo
#define meshtastic_FromRadio_payload_variant_node_info_MSGTYPE meshtastic_NodeInfo
#define meshtastic_FromRadio_payload_variant_metadata_MSGTYPE meshtastic_DeviceMetadata

extern const pb_msgdesc_t meshtastic_Position_msg;
extern const pb_msgdesc_t meshtastic_User_msg;
extern const pb_msgdesc_t meshtastic_Data_msg;
extern const pb_msgdesc_t meshtastic_MeshPacket_msg;
extern const pb_msgdesc_t meshtastic_MyNodeInfo_msg;
extern const pb_msgdesc_t meshtastic_NodeInfo_msg;
extern const pb_msgdesc_t meshtastic_DeviceMetadata_msg;
extern const pb_msgdesc_t meshtastic_ToRadio_msg;
extern const pb_msgdesc_t meshtastic_FromRadio_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define meshtastic_Position_fields &meshtastic_Position_msg
#define meshtastic_User_fields &meshtastic_User_msg
#define meshtastic_Data_fields &meshtastic_Data_msg
#define meshtastic_MeshPacket_fields &meshtastic_MeshPacket_msg
#define meshtastic_MyNodeInfo_fields &meshtastic_MyNodeInfo_msg
#define meshtastic_NodeInfo_fields &meshtastic_NodeInfo_msg
#define meshtastic_DeviceMetadata_fields &meshtastic_DeviceMetadata_msg
#define meshtastic_ToRadio_fields &meshtastic_ToRadio_msg
#define meshtastic_FromRadio_fields &meshtastic_FromRadio_msg

/* Maximum encoded size of messages (where known) */
#define MESHTASTIC_WAYMESH_MESH_PB_H_MAX_SIZE    meshtastic_FromRadio_size
#define meshtastic_Data_size                     265
#define meshtastic_DeviceMetadata_size           59
#define meshtastic_FromRadio_size                333
#define meshtastic_MeshPacket_size               324
#define meshtastic_MyNodeInfo_size               18
#define meshtastic_NodeInfo_size                 144
#define meshtastic_Position_size                 39
#define meshtastic_ToRadio_size                  327
#define meshtastic_User_size                     79

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
