/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "waymesh_mesh.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(meshtastic_Position, meshtastic_Position, AUTO)


PB_BIND(meshtastic_User, meshtastic_User, AUTO)


PB_BIND(meshtastic_Data, meshtastic_Data, 2)


PB_BIND(meshtastic_MeshPacket, meshtastic_MeshPacket, 2)


PB_BIND(meshtastic_MyNodeInfo, meshtastic_MyNodeInfo, AUTO)


PB_BIND(meshtastic_NodeInfo, meshtastic_NodeInfo, AUTO)


PB_BIND(meshtastic_DeviceMetadata, meshtastic_DeviceMetadata, AUTO)


PB_BIND(meshtastic_ToRadio, meshtastic_ToRadio, 2)


PB_BIND(meshtastic_FromRadio, meshtastic_FromRadio, 2)



